/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(async_fich_parser.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(524697181de5cc0b4265276740c64fc6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ysf2/async_fich_parser.h>
// pydoc.h is automatically generated in the build directory
#include <async_fich_parser_pydoc.h>

void bind_async_fich_parser(py::module& m)
{

    using async_fich_parser    = gr::ysf2::async_fich_parser;


    py::class_<async_fich_parser, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<async_fich_parser>>(m, "async_fich_parser", D(async_fich_parser))

        .def(py::init(&async_fich_parser::make),
           D(async_fich_parser,make)
        )
        



        ;




}








