/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fich_parser_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f1c135ab795a7d94ec3fb5ee50ce7242)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ysf2/fich_parser_b.h>
// pydoc.h is automatically generated in the build directory
#include <fich_parser_b_pydoc.h>

void bind_fich_parser_b(py::module& m)
{

    using fich_parser_b    = gr::ysf2::fich_parser_b;


    py::class_<fich_parser_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fich_parser_b>>(m, "fich_parser_b", D(fich_parser_b))

        .def(py::init(&fich_parser_b::make),
           D(fich_parser_b,make)
        )
        



        ;




}








