/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ysf2
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_YSF2_API_H
#define INCLUDED_YSF2_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ysf2_EXPORTS
#define YSF2_API __GR_ATTR_EXPORT
#else
#define YSF2_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_YSF2_API_H */
